#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.10

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - mkdir -p ~/.pip  
            - echo -e "[global]\nindex-url = https://pypi.org/simple" > ~/.pip/pip.conf
            - pip install --upgrade pip
            - pip install pytest
            - pip install -e .
            - pytest -v cyclarity_in_vehicle_sdk/tests/* --junitxml=test-reports/report.xml
