name: Deploy to PyPI

on: 
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    environment: pypi-deploy
    container:
      image: public.ecr.aws/p0d9j9b5/invehicle/dockers:3.10.13-2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to PyPI 
        env: 
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }} 
        run: ./scripts/pipeline_deploy_pypi.sh 